# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Deploy
  jobs:
  - job: DeployResourceGroup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: '<YourServiceConnectionName>'
        subscriptionId: '<YourSubscriptionId>'
        location: 'West US'
        templateLocation: 'Linked artifact'
        csmFile: 'deployment/azure/template.json'
        csmParametersFile: 'deployment/azure/parameters.json'
        deploymentMode: 'Incremental'
